# Generated by Django 4.0.3 on 2022-07-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('block_time', models.DateTimeField()),
                ('bad_request_count', models.IntegerField()),
            ],
        ),
    ]
