# Generated by Django 4.0.3 on 2022-07-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestip',
            name='bad_request_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestip',
            name='block_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
