# Generated by Django 4.0.3 on 2022-07-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0002_alter_requestip_bad_request_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestip',
            name='bad_request_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
